### ISSUE TITLE
[BUG] MacOS CLI tool \r\n (CRLF) executables line breaks

### ISSUE THREAD

**Issue by crawler** [MarcusCemes/image-processing-pipeline#16]
**Describe the bug**
Due to CRLF line breaks in the executable file, the CLI tool not works. And if I open ipp executable and change line breaks to LF then it works fine.

**To Reproduce**
On macOS
`$ yarn global add @ipp/cli`
`$ ipp`
**Expected behaviour**
execution

**Screenshots**
![Screen Shot 2020-08-31 at 2 32 29 PM](https://user-images.githubusercontent.com/754795/91716224-dedf8100-eb97-11ea-946b-8e633865d562.png)
![Screen Shot 2020-08-31 at 2 29 51 PM](https://user-images.githubusercontent.com/754795/91716228-e1da7180-eb97-11ea-82d8-bbb5b3a0c412.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 10.15.6
 - Shell: Zsh

**Additional context**
This can be solved by simply replacing \r\n with \n through all project source files or in the executable only. And changing project .vscode/settings.json

I can create a pull request if you want.

**Comment by MarcusCemes** [comment]
This should be resolved in `@ipp/cli@1.1.1`.

Git automatically handles line endings, but typescript compilation will use the platform default for generated `.js` files, regardless of source line endings. Publishing to npm will preserve the line endings.

I've added a temporary pre-publish script to fix the bin script until a Linux-based CI publish is setup.
