### ISSUE TITLE
Angular integration

### ISSUE THREAD

**Issue by alois-reinstadler** [MarcusCemes/image-processing-pipeline#21]
**I love what you built!**
I do most of my work in Angular and have been trying to get this bad boy up and running using ipp, but I can't figure out how or even if it's possible to do.

Are there any updates on using it with angular?

**Comment by MarcusCemes** [comment]
At the moment, IPP is focussed on the generation of images in a platform and framework agnostic way.

There is nothing special required to integrate this with Angular, you can either use the CLI approach to generate images and serve them from the assets folder or try and modify the Webpack config of your application to make use of the `@ipp/webpack` loader that lets you import images into your code, providing generated URLs.

For the latter, there are some [code samples](https://ipp.vercel.app/docs/webpack/frontend) in the documentation for consuming the import in React and Vue and there is also [an article](https://dev.to/angular/automatic-adaptive-images-in-angular-applications-1ebf) that explains some of the concepts using the predecessor of IPP.

My Angular knowledge is very limited, if you could provide a reusable picture component for a `SimpleExport` input (such as the examples above), I could add them to the documentation. There is no standard when it comes to handling images in frameworks, hence the various interfaces offered by IPP.
