### ISSUE TITLE
Can't install IPP on Mac M1 because sharp version is too old

### ISSUE THREAD

**Issue by marcfilleul** [MarcusCemes/image-processing-pipeline#33]
Hi,

I know IPP is not actively maintained but it's by far the best library I've found and used for processing images and I'm stuck with my M1 Mac :(

M1 Mac support came in sharp 0.29 and IPP still uses 0.27.

I've tried to update sharp to 0.30 in my IPP fork but wasn't able to install it correctly in my project.

If by any chance you have some time to update some sharp dependencies, it would be great.

Thanks in advance.

Best regards.

**Comment by MarcusCemes** [comment]
Hi,

Thanks for letting me know! I'm glad to hear it.

I'll see if I can get around to doing a full dependency upgrade this upcoming week, it shouldn't be too hard, but I might need to revive/fix the CI deployment pipeline.

This repository has been getting some attention this week, I'm curious as to how you came across it?

**Comment by marcfilleul** [comment]
That would be awesome, thanks!

I was already a happy user of RIB starting 2 years ago I think. 
Then switched to IPP so I'm not really a new user ;)

**Comment by MarcusCemes** [comment]
Would you mind trying the newly published version?

**Comment by marcfilleul** [comment]
With pleasure!

I was able to install it without error 😀
But running the script failed 😭

Here are the errors I got (errors.json).

For a simple transform:
`[{"name":"PipelineException","message":"Could not resolve pipe: {\"resolve\":\"@ipp/compress\",\"module\":\"CompressPipe\"}"}]`

For a more complex one with Trace:
`[{"name":"PipelineException","message":"Could not resolve pipe: {\"resolve\":\"@ipp/trace\",\"module\":\"TracePipe\"}"}]`

I got one error line for each image in my input folder and the error is on the first resolve found in the config.

I've used the same config I was using back in the time but if you need my config file to check it, I will send it to you.

**Comment by MarcusCemes** [comment]
Did you install the `@ipp/compress` and `@ipp/trace` packages?

Those pipes are available as separate packages due to the size of their dependencies.

**Comment by marcfilleul** [comment]
My bad, I forgot to install the packages.

Now it's better, I have this warning but it's not a big deal:

`warning @ipp/compress > imagemin-mozjpeg > mozjpeg > bin-build > tempfile > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.`

I managed to install the Primitive package without error but I have an error when trying to use it:

`[{"name":"PipelineException","message":"[@ipp/primitive.PrimitivePipe] Command failed with ENOENT: /Users/marco/webdev/11ty-starter/node_modules/@ipp/primitive/vendor/primitive-darwin-arm64 -i - -o - -n 16 -m 1 -a 128 -j 1\nspawn /Users/marco/webdev/11ty-starter/node_modules/@ipp/primitive/vendor/primitive-darwin-arm64 ENOENT"}]`

Do you know what could cause this?

**Comment by MarcusCemes** [comment]
The warning is OK.

`@ipp/primitive` uses a library written in Go, the package ships pre-compiled binaries for arm64, I need to also modify the `build-vendor.js` script to start shipping arm64.

In the meantime, you can take a look at [build-vendor.js](https://github.com/MarcusCemes/image-processing-pipeline/blob/527ed0d563e6bc936ff39845fcb06f7a41567fce/packages/primitive/scripts/build-vendor.js) and compile [fogleman/primitive](https://github.com/fogleman/primitive) for arm64 yourself, and place it in the `vendor` directly as shown in the error message.

**Comment by MarcusCemes** [comment]
There's a new version of `@ipp/primitive` (v1.1.7), give it a try.

**Comment by marcfilleul** [comment]
Thank you.
I won't be able to compile anything unfortunately 😔.

`@ipp/primitive` v1.1.7 install failed, here are the logs:

```bash
yarn add -D @ipp/primitive
yarn add v1.22.18
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > quicklink@2.2.0" has unmet peer dependency "react@^16.8.0".
warning " > quicklink@2.2.0" has unmet peer dependency "react-dom@^16.8.0".
warning "@ipp/cli > rxjs-hooks@0.7.0" has incorrect peer dependency "react@17.0.1".
warning "@ipp/cli > rxjs-hooks@0.7.0" has incorrect peer dependency "rxjs@^6.5.3".
[4/4] 🔨  Building fresh packages...
[1/5] ⠂ esbuild
[2/5] ⠂ sharp
[3/5] ⠂ mozjpeg
[4/5] ⠂ pngquant-bin
error /Users/marco/webdev/11ty-starter/node_modules/@ipp/primitive: Command failed.
Exit code: 1
Command: node ./scripts/check-executable.js
Arguments: 
Directory: /Users/marco/webdev/11ty-starter/node_modules/@ipp/primitive
Output:
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '/Users/marco/webdev/11ty-starter/node_modules/@ipp/primitive/scripts/check-executable.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
```

**Comment by MarcusCemes** [comment]
The release configuration had to be modified, v1.1.8 should fix that.

**Comment by marcfilleul** [comment]
Thank you, v1.1.8 install worked.

Unfortunately I have a new error when running primitive pipe:

```json
[{"name":"PipelineException","message":"[@ipp/primitive.PrimitivePipe] Command failed with EACCES: /Users/marco/webdev/11ty-starter/node_modules/@ipp/primitive/vendor/primitive-darwin-arm64 -i - -o - -n 16 -m 1 -a 128 -j 1\nspawn /Users/marco/webdev/11ty-starter/node_modules/@ipp/primitive/vendor/primitive-darwin-arm64 EACCES"}]
```

**Comment by MarcusCemes** [comment]
npm seemed to be wiping executable permission bits from CI, I still have no idea why.

v1.1.11 runs a post-install script that should reinstate them. Third time's a charm?

**Comment by marcfilleul** [comment]
Thank you very much, it worked indeed!

I have on last question now it's working.
Is there anyway to setup primitive flags to tweak some options?

**Comment by marcfilleul** [comment]
Great!
Thank you very much for updating IPP.

Beyond my own need, I think it deserves it 😁

Best regards
